<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DAP.TestCRM.E2E.Common/DAP.TestCRM.E2E.Common.csproj" />
    <ProjectReference Include="../../src/DAP.Core/DAP.Core.csproj" />
    <ProjectReference Include="../../src/DAP.Data.Sqlite/DAP.Data.Sqlite.csproj" />
  </ItemGroup>
</Project>
