<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DAP.Core/DAP.Core.csproj" />
    <ProjectReference Include="../../src/DAP.Runtime.Web/DAP.Runtime.Web.csproj" />
  </ItemGroup>
</Project>
